version: "3.9"
networks:
    skv_test:
        external: false

services:
    database:
        image: "postgres:14.2-alpine"
        env_file: "test.env"
        networks:
            - "skv_test"
    skv_test:
        env_file: "test.env"
        networks:
            - "skv_test"
        build:
            context: ".."
            dockerfile: "./docker/Dockerfile.test"
