---
name: "Install dependencies"
description: "Installs dependencies and setups Node.JS"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
      shell: "bash"