---
name: Release all
on:
  push:
    tags:
      - '*'
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
        shell: "bash"
  build-lint:
    needs: ["deps"]
    strategy:
      matrix:
        action: [build, lint]
    runs-on: ubuntu-latest
    name: Run ${{ matrix.action }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        uses: ./.github/workflows/common-node
      - name: Run ${{ matrix.action }}
        run: npm run ${{ matrix.action }}
  test:
    runs-on: ubuntu-latest
    needs: ["deps"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: skv-test
          POSTGRES_USER: skv-test
          POSTGRES_DB: skv-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        uses: ./.github/workflows/common-node
      - name: Test code
        run: npm run test
        env:
          POSTGRES_DB: skv-test
          POSTGRES_USER: skv-test
          POSTGRES_PASSWORD: skv-test
  gendocs:
    runs-on: ubuntu-latest
    needs: ['build-lint', 'test']
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        uses: ./.github/workflows/common-node
      - name: Generate documentation using typedoc
        run: npm run gendocs
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Gen changelog
        run: bash .github/bin/genlog.sh
      - id: tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF##*/})
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body_path: 'changelog.txt'
          draft: false
