---
name: Test code
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    strategy:
      matrix:
        action: [build, lint, test]
    runs-on: ubuntu-latest
    name: Run ${{ matrix.action.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        uses: ./.github/workflows/common-node
      - name: Build
        run: npm run ${{ matrix.action.name }}
